// app/layout.tsx or app/layout.js
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import './globals.css';
import Menu from "./homepage_sections/menu";
import Provider from "@/components/Provider";
import Head from "next/head";
import { Noto_Sans_Bengali } from 'next/font/google';

// const notoBengali = Noto_Sans_Bengali({
//   weight: ['400', '700'],
//   subsets: ['bengali'],
//   display: 'swap',
// });

export const metadata = {
  title: "Crime Vision",
  description: "Generated by Mathmozo IT",
  openGraph: {
    title: 'Acme',
    description: 'Acme is a ...'
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body className={`text-base font-solaiman`}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
